export const CALL_UPDATE_FAVORITE = 'CALL_UPDATE_FAVORITE';
export const UPDATE_FAVORITE = 'UPDATE_FAVORITE';
export const ADD_TO_FAVORITE = 'ADD_TO_FAVORITE';
export const REMOVE_FROM_FAVORITE = 'REMOVE_FROM_FAVORITE';