export const FETCHING_AUTOCOMPLETE_DATA = 'FETCHING_AUTOCOMPLETE_DATA';
export const SEARCH_AUTOCOMPLETE_DATA = 'SEARCH_AUTOCOMPLETE_DATA';
export const ERROR_AUTOCOMPLETE_DATA = 'ERROR_AUTOCOMPLETE_DATA';