export const FETCHING_CURRENT_WEATHER_DATA = 'FETCHING_CURRENT_WEATHER_DATA';
export const SEARCH_CURRENT_WEATHER_DATA = 'SEARCH_CURRENT_WEATHER_DATA';
export const ERROR_CURRENT_WEATHER_DATA = 'ERROR_CURRENT_WEATHER_DATA';
export const CELSIUS_CURRENT_WEATHER_DATA = 'CELSIUS_CURRENT_WEATHER_DATA';